pages:
  stage: deploy
  environment: production
  script:
    - echo "开始下载node环境"
    - wget -O /usr/temp https://mirrors.aliyun.com/nodejs-release/v14.12.0/node-v14.12.0-linux-arm64.tar.xz
    - tar xf /usr/temp/node-v14.12.0-linux-arm64.tar.xz -C /usr/local
    - export PATH=$PATH:/usr/temp/node-v14.12.0-linux-arm64
    - echo "修改镜像为阿里镜像"
    - npm set config registry http://registry.npmmirror.com
    - echo "开始获取源文档地址"
    - git clone https://gitee.com/usernameisregistered/passerby.git
    - echo "完成获取源文档地址"
    - echo "开始安装依赖"
    - npm install
    - echo "完成安装依赖"
    - echo "开始构建页面"
    - npm run build
    - echo "完成构建页面"
    - echo "开始发布站点： $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH