
include:
  - component: gitlab.com/to-be-continuous/node/gitlab-ci-node@3.15.2
    # 2: set/override component inputs
    inputs:
      image: "registry.hub.docker.com/library/node:14" # ⚠ this is only an example
      lint-enabled: "true"

pages:
  stage: deploy
  environment: production
  script:
    - echo "修改镜像为阿里镜像"
    - npm set config registry http://registry.npmmirror.com
    - echo "开始获取源文档地址"
    - git clone https://gitee.com/usernameisregistered/passerby.git
    - echo "完成获取源文档地址"
    - echo "开始安装依赖"
    - npm install
    - echo "完成安装依赖"
    - echo "开始构建页面"
    - npm run build
    - echo "完成构建页面"
    - echo "开始发布站点： $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH